### PR TITLE
added check for "audioWorklet"

### LINKED ISSUE #19: audioWorklet is not defined - Chrome Android 73
This is a strange one I picked up today, it seems (my) Chrome Android 73 implementation does define `AudioWorkletNode`, but not `AudioContext.audioWorklet`, as if it was an incomplete implementation. However, this polyfill only checks for `AudioWorkletNode`, and thus there is a runtime error.

The solution I came up was the following, on https://github.com/GoogleChromeLabs/audioworklet-polyfill/blob/master/src/index.js#L22

```
if (typeof AudioWorkletNode !== 'function' || !("audioWorker" in AudioContext.prototype)) {
```

### PR DESCRIPTION
**Pull request by JohnWeisz**
fixes https://github.com/GoogleChromeLabs/audioworklet-polyfill/issues/19

### CODE REVIEW

**Comment by JohnWeisz** [comment]
CLA signed

**Comment by therewasaguy** [comment]
Hi @developit, are you able to review this one line change? It fixes an issue on insecure origins like debugging localhost on an Android. More info at https://github.com/GoogleChromeLabs/audioworklet-polyfill/issues/19 and https://github.com/processing/p5.js-sound/issues/409

Thanks for your work on this library! And thank you @JohnWeisz for identifying this issue!

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Thanks folks, sorry for the slow merge!

**Comment by catarak** [comment]
@developit thanks for merging this in! Is this PR going to be included in a release soon? It would be great to get this PR in a release, especially since there hasn't been a release since 2018!

**Pull request merged**
