### PR TITLE
Make AudioWorkletProcessor a class (fixes #24)

### LINKED ISSUE #24: Error in iOS Safari 12
On iOS Safari 12, audio processors can't extend `AudioWorkletProcessor` because it's not a class with a prototype object.

### Error and stack trace

TypeError: The value of the superclass's prototype property is not an object.

1. Eval Code
2. eval
3. about:blank:2:2231
4. (anonymous function) — index.js:86
5. promiseReactionJob

This is the offending line https://github.com/GoogleChromeLabs/audioworklet-polyfill/blob/master/src/index.js#L86. which is (unsurprisingly) the line that `eval`s the processor.

### PR DESCRIPTION
**Pull request by hgcummings**
Fix for issue #24

### CODE REVIEW

**Comment by hgcummings** [comment]
@googlebot I signed it!

**Comment by developit** [comment]
Thanks for the PR! We might need to use a hack here to fall back to a function in older browsers. Currently I think the class will actually end up being transpiled to a function by this project's build script, but I can tweak that.

**Comment by hgcummings** [comment]
Ah, on closer inspection I think this PR is unnecessary...

Functions would have a prototype object anyway, so a plain old function should be fine.

I saw this error when working from source to implement #26 , but I wasn't being consistent with how you're transpiling your distributed package, so my build chain was leaving this line as-is, which I think results in a named lambda (which has no prototype property) rather than a plain old JS function (which has a prototype property and works just fine).

Re-tested on iOS Safari 12. Nothing to do here.

**Comment by charlieroberts** [comment]
@hgcummings I also had this problem. I fixed it by making a function and assigning an empty object to its`.prototype` property, and then assigning this function to the `AudioWorkletProcessor` member of the context. Your fix would have saved me a lot of debugging... are you sure this should be closed? I don't quite follow what you mentioned about transpiling.

**Comment by hgcummings** [comment]
@charlieroberts are you referencing the distributed minified version (e.g. from npm) or the raw source (e.g. from GitHub)? I only had this problem with the latter.

The issue was the following expression:

```
          AudioWorkletProcessor () {
            this.port = nextPort;
          }
```

The transpiler/bundler used to generate the distributed version of audioworklet-polyfill (microbundle) turns the above expression into a plain-old JS function, which has a prototype property. The transpiler/bundler I was using (rollup) turned the above expression into a lambda function (which doesn't have a prototype property).

The above expression is pretty weird-looking to me. I don't recognise it as valid syntax for declaring a function, class, or lambda. Which might explain why different transpilers interpret it differently.

My change to explicitly declare a class was unnecessarily disruptive (materially altered the output of microbundle). A change like yours to explicitly declare a function would be safer (wouldn't materially alter the output of microbundle, and should make other transpilers match it more closely), and is probably still worth submitting as a PR.

**Comment by charlieroberts** [comment]
Yes, I was using the raw code, and I got this error even without any modifications from my bundler (Browserify). At this point my version is getting kinda far from the polyfill (for example, supporting variable buffer sizes to mimic the `AudioContext.latencyHint` behavior) and I'm not familiar with microbundle (looks nice!) so it might take some time to create a tested pull request, but I'll add it to the list :) Thanks for the explanation @hgcummings !

**Comment by hgcummings** [comment]
Yeah, I think that matches what I saw. When I said "my bundler turns this expression into a lambda function" I think actually my bundler wasn't touching this expression at all, and Safari was interpreting it as a lambda declaration. Like I say, I don't recognise it as valid pure ES, at least not in older ES versions, so I'm not surprised it gets interpreted a bit inconsistently.

**Pull request closed without merging**
